#!/bin/sh

TARGET=

if [ "$1" == "--cflags" ]
then
	echo "-I/Users/me/dev/openttd/trunk/projects/openttd/include"
elif [ "$1" == "--prefix" ]
then
	echo "/Users/me/dev/openttd/trunk/projects/openttd"
elif [ "$1" == "--cppflags" ]
then
	echo ""
elif [ "$1" == "--version" ]
then
	echo "fake"
else
	echo "-L/Users/me/dev/openttd/trunk/projects/openttd/lib -lpng"
fi
